name: Daily Stock ETL
on:
  schedule:
    - cron: '0 8 * * *' # Runs at 8:00 AM UTC
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy yfinance pyarrow sqlalchemy pymysql

      - name: Run ETL Script
        run: python stock_risk_analysis.py # Change this to your filename
